version: '{build}'
os: Visual Studio 2015
init: []
install:
- git submodule update --init --recursive
build_script:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- mkdir build
- cd build
- cmake --version
- cmake ../Tests -G "Visual Studio 14 2015"
- cmake --build . --config Release
test_script:
- Release\Tests.exe
